config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  namespace :api do
    namespace :v1 do
      resources :comments
    end
  end
  # Defines the root path route ("/")
  devise_for :users

  root to: "users#index"
  # get '/users/:user_id/posts/:id/likes', to: 'likes#create', as: 'user_post_likes'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new,:index, :show, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

 get '/api/users', to: 'api_users#index'
 get "/api/users/:id", to: "api_users#show"
 get '/api/users/:user_id/posts', to: 'api_posts#index'
 get '/api/users/:user_id/posts/:post_id/comments', to: 'api_comments#index'
 post '/api/users/:user_id/posts/:post_id/comments', to: 'api_comments#create'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    return unless user.present?

    can :create, [Comment, Post]
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Comment, author: user
      can :destroy, Post, author: user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :text, presence: true

  after_save :update_comment_counter
  # A method that updates the comments counter for a post.
  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  validates :author, uniqueness: { scope: :post, message: "You can't like a post more than once" }
  validates :author, presence: true
  validates :post, presence: true
  after_save :update_like_counter

  # A method that updates the likes counter for a post.
  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_save :update_post_counter
  after_destroy :update_post_counter
  # A method that updates the posts counter for a user.
  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  # A method which returns the 5 most recent comments for a given post.
  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :liked_posts, through: :likes, source: :post
  validates :name, presence: true
  validates :photo, presence: true
  validates :bio, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api_comments_controller.rb
class ApiCommentsController < ActionController::API
  before_action :set_post, only: %i[new create update]
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comments = @post.comments
    render json: @comments
  end

  def create
    @comment = Comment.new(author_id: params[:user_id].to_i, post_id: params[:post_id].to_i, text: params[:text])
    if @comment.save
      render json: @comment, status: 201
    else
      render json: { errors: @comment.errors.full_messages }, status: 400
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/api_posts_controller.rb
class ApiPostsController < ActionController::API
  before_action :find_user
  def index
    @posts = @user.posts
    render json: @posts
  end

  private

  def find_user
    # @user = User.find(params[:user_id])
    @user = User.includes(:posts, posts: [:comments, { comments: [:author] }]).find(params[:user_id])
  end
end

app/controllers/api_users_controller.rb
class ApiUsersController < ActionController::API
  def index
    @users = User.all
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    render json: @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: %i[new create update]
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(user_id: @post.author.id, id: @post.id), notice: 'Comment added successfully'
    else
      flash.now[:alert] = @comment.errors.full_messages.first if @comment.errors.any?
      render :new, status: 400
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @user = @post.author
    @comment.destroy
    redirect_to user_post_path(@user, @post), notice: 'Comment was successfully deleted'
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    @like.save
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end

  def destroy
    @like = current_user.likes.find(params[:user_id])
    @like.destroy
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :find_user, only: %i[index show new edit create]
  def index
    @posts = @user.posts.includes(:comments).order(created_at: :asc)
  end

  def show
    @post = @user.posts.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_posts_path(current_user), notice: 'Post created successfully'
    else
      flash.now[:alert] = @post.errors.full_messages.first if @post.errors.any?
      render :new, status: 400
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'Post deleted successfully'
    else
      flash.new[:alert] = @post.errors.full_messages.first if @post.errors.any?
      render :show, status: 400
    end
  end

  private

  def find_user
    # @user = User.find(params[:user_id])
    @user = User.includes(:posts, posts: [:comments, { comments: [:author] }]).find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h1>Edit comments<h1>

app/views/comments/index.html.erb
<h1>Here are list of comments for given user and post<h1>

app/views/comments/new.html.erb
<h1>Create new comments<h1>
<%= form_with model: @comment, url: user_post_comments_path, local: true do |form| %>
  <%= form.text_field :text, class: "comment_field", placeholder: "Add your comment" %>
  <%= form.submit "Add comment", class: "submit_btn" %>
<% end %>

app/views/comments/show.html.erb
<h1>list a comment for given user id, post id<h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render partial: "shared/header" %>
  <br/>
  <div class="container">
      <p class="notice"><%= notice %></p> 
      <p class="alert"><%= alert %></p>
     <%= yield %>
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/edit.html.erb
<h1>Edit like<h1>

app/views/likes/index.html.erb
<h1>List of likes<h1>

app/views/likes/new.html.erb
<h1>Create likes<h1>

app/views/likes/show.html.erb
<h1>List of likes<h1>

app/views/posts/edit.html.erb
<h1>Edit posts<h1>

app/views/posts/index.html.erb
<div class="container border">
  <div class="row">
    <div class="col-md-4 p-3" >
      <div class="img-cover text-center">
        <img src="<%= @user.photo%>" alt="not found" width="180">
      </div>
    </div>
    <div class="col-md-8 p-3" >
      <div class="border p-4"><h3><%= @user.name%></h3>
      <%if can? :create, Post%>
        <%= button_to "New post", new_user_post_path(user_id: @user.id), method: :get, class: "btn-primary" %>
      <%end%>
      <h6 class="pull-right text-right">Number of posts:<%=@user.posts_counter%></h6></div>
    </div>
  </div>
  <% @posts.each_with_index do |post,index| %>
    <div class="row mt-1 mb-1">
      <div class="col-md-12">
        <div class="border p-2">
          <h4><%= link_to "#{post.title}", user_post_path(id:post.id) %></h4>
          <p>
            <%= post.text %>
          </p>
          <p class="text-right m-0"><small>Comments:<%=post.comments_counter %></small>,<small>Likes:<%=post.likes_counter %></small></p>
        </div>
      </div>
    </div>
   <% post.recent_comments.each do |comment| %>
      <div class="row">
        <div class="col-md-12">
          <div class="border p-2">
            <p class="text-left m-0"><small><%= comment.author.name %></small> : <small><%= comment.text %></small></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-12 text-center m-1">
      <button class="btn btn-secandary">Pagination</button>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create posts</h1>
<%= form_with model: @post, url: user_posts_path, local: true do |form| %>
  <%= form.text_field :title, class: "form_title", placeholder: "Enter your title here" %><br>
  <%= form.text_area :text, class: "form_text", placeholder: "Enter your text here" %><br>
  <%= form.submit  class: "submit_btn" %>
<% end %>

app/views/posts/show.html.erb
<div class="container border">
   <div class="row mt-1 mb-1">
    <div class="col-md-12">
      <div class="border p-2">
      <div class="btn_container">
      </div>
        <% if can? :create, @post %>
          <%= render partial: "shared/like", locals: { like: Like.new, post_id: @post.id, user_id: @post.author.id } %>
          <%= button_to "Comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id), method: :get, class: "add_comment" %>
        <% end %>
        <div class="d-flex justify-content-between"><h4 class="m-1"><%= @post.title %></h4>
          <p class="text-right m-1 bg-primary"><small>Comments:<%=@post.comments_counter %></small>,<small>Likes:<%=@post.likes_counter %></small></p>
        </div>
        <p>
          <%= @post.text %>
        </p>
        <% if can? :delete, @post %>
          <%= button_to "Delete", @resource,form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete%>
        <% end %>
      </div>
    </div>
  </div>
   <div class="row">
    <div class="col-md-12">
      <div class="border pl-1">
        <% @post.comments.each do |comment| %>
          <p class="text-left m-0"><small><%= comment.author.name %></small> : <small><%= comment.text %></small></p>
          <% if can? :delete, @post %>
          <%= button_to 'Delete comment', user_post_comment_path(current_user, @post, comment), method: :delete, class: 'delete-btn' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-0">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to "Home", users_path, class:"nav-item nav-link" %>
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-item nav-link" %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link bg-dark border-0" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class:"nav-item nav-link" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-item nav-link" %>
        <% end %>
    </div>
  </div>
</nav>

app/views/shared/_like.html.erb
<%= form_with model: @like, url: user_post_likes_path(user_id: @user, post_id: @post), local: true do |form| %>
  <%= form.submit "Like" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user<h1>

app/views/users/index.html.erb
<div class="container border">
  <% @users.each do |friend| %>
    <div class="row">
    <div class="col-md-4 p-3" >
      <div class="img-cover text-center ">
        <img src="<%= friend.photo %>" width="180" alt="not found">
      </div>
    </div>
    <div class="col-md-8 p-3" >
      <div class="border p-4"><h3><%= link_to friend.name, user_path(friend) %></h3>
      <h6 class="pull-right text-right">Number of posts:<%=friend.posts_counter %></h6></div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Create new user</h1>

app/views/users/show.html.erb
<div class="container border">
  <div class="row">
    <div class="col-md-4 p-3" >
      <div class="img-cover text-center ">
        <img src="<%= @user.photo%>" alt="not found" width="180">
      </div>
    </div>
    <div class="col-md-8 p-3" >
      <div class="border p-4"><h3><%= link_to "#{@user.name}", user_path(@user)%></h3>
      <%if can? :create, Post%>
        <%= button_to "New post", new_user_post_path(user_id: @user.id), method: :get, class: "btn-primary" %>
      <%end%>
      <h6 class="pull-right text-right">Number of posts:<%=@user.posts_counter%></h6></div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="border p-2">
        <h4>Bio</h4>
        <p>
          <%= @user.bio%>
        </p>
      </div>
    </div>
  </div>
  <% @user.recent_posts.each_with_index do |post,index|%>
    <div class="row mt-1 mb-1">
      <div class="col-md-12">
        <div class="border p-2">
          <h4><%= link_to "#{post.title}", user_post_path(user_id:post.author_id,id:post.id) %></h4>
          <p>
            <%= post.text%>
          </p>
          <p class="text-right m-0"><small>Comments: <%=post.comments_counter%></small>,<small>Likes: <%=post.likes_counter%></small></p>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12 text-center m-1">
      <button class="btn btn-secandary"><%= link_to "See more posts", user_posts_path(user_id:@user.id) %></button>
    </div>
  </div>
</div>